### ISSUE TITLE
GitHub buttons missing on site

### ISSUE THREAD

**Issue by morancj** [TrustedFirmwareWebsite/website#174]
Other websites hosted by Linaro have three buttons at the bottom of each page: a link to the GitHub repository for the site, "Report an issue" and "Edit on GitHub":
![image](https://user-images.githubusercontent.com/25228551/68850298-aa174180-06cb-11ea-911d-a622da1b3840.png)
They are not present on this site: can these be added?

**Comment by kylekirkby** [comment]
@bfletcher @mcarlini
